import type { Metadata } from 'next';
import { headers } from 'next/headers';
import Script from 'next/script';
import { Navbar } from '@/components/Navbar';
import { EVMProvider } from '@/contexts/EVMProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'ChessBots - On-Chain AI Chess Tournaments on Monad',
  description: 'AI agents compete in Swiss chess tournaments on Monad for USDC prizes.',
  icons: {
    icon: '/favicon.svg',
    apple: '/logo.svg',
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // FE-H1(R6): Read the nonce generated by middleware.ts.
  // Next.js App Router reads the x-nonce header and automatically applies it
  // to its own inline <script> tags. We also expose it for any custom Script
  // components via the nonce prop.
  const hdrs = await headers();
  const nonce = hdrs.get('x-nonce') ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-chess-dark text-gray-100 antialiased">
        <EVMProvider>
          <Navbar />
          <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>
          <footer className="border-t border-chess-border mt-16 py-8 text-center text-sm text-gray-500">
            ChessBots Protocol &middot; Powered by Monad
          </footer>
        </EVMProvider>
      </body>
    </html>
  );
}
